<a href="https://colab.research.google.com/github/yaminabeworks/qiitakiji/blob/main/numpyknock_recsys02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# recsys-python

推薦システムを作ることで、機械学習を学ぶ。

https://recsyslab.github.io/recsys-python/

## 第1章 評価履歴

準備

In [1]:
import numpy as np

## 評価履歴

### 01 評価履歴の生成

1. `np.nan`を使う。
2. `np.array`を使う。

In [2]:
Du_list = [[5, 3, 1],
           [6, 2, 1],
           [4, 1, 1],
           [8, 5, -1],
           [2, 4, -1],
           [3, 6, -1],
           [7, 6, -1],
           [4, 2, np.nan],
           [5, 1, np.nan],
           [8, 6, np.nan],
           [3, 4, np.nan],
           [4, 7, np.nan],
           [4, 4, np.nan]]

Du = np.array(Du_list)

In [3]:
print(f'Du = \n{Du}')

Du = 
[[ 5.  3.  1.]
 [ 6.  2.  1.]
 [ 4.  1.  1.]
 [ 8.  5. -1.]
 [ 2.  4. -1.]
 [ 3.  6. -1.]
 [ 7.  6. -1.]
 [ 4.  2. nan]
 [ 5.  1. nan]
 [ 8.  6. nan]
 [ 3.  4. nan]
 [ 4.  7. nan]
 [ 4.  4. nan]]


### 02 評価履歴の形状

- `np.shape`を使う。

In [4]:
print(f'Duの形状 = {Du.shape}')

Duの形状 = (13, 3)


### 03 評価履歴の行数

- `np.shape`を使う。

In [5]:
print(f'Duの行数 = {Du.shape[0]}')

Duの行数 = 13


### 04 評価履歴の列数

- `np.shape`を使う。

In [6]:
print(f'Duの列数 = {Du.shape[1]}')

Duの列数 = 3


### 05 評価履歴の全要素数

- `np.size`を使う。
  - おそらく、`np.shape[0]*np.shape[1]`でもよい。

In [7]:
print(f'Duの全要素数 = {Du.size}')

Duの全要素数 = 39


## アイテム

### 06 アイテム集合

アイテムは、インデックスと読み替えてもこの場合差し支えなさそう。

In [8]:
I = np.arange(Du.shape[0])
print(f'I = {I}')

I = [ 0  1  2  3  4  5  6  7  8  9 10 11 12]


### 07 アイテムの特徴ベクトルの集合

numpy行列中にある評価値以外を取り出す。

In [9]:
x = Du[:, :-1]
print(f'x = \n{x}')

x = 
[[5. 3.]
 [6. 2.]
 [4. 1.]
 [8. 5.]
 [2. 4.]
 [3. 6.]
 [7. 6.]
 [4. 2.]
 [5. 1.]
 [8. 6.]
 [3. 4.]
 [4. 7.]
 [4. 4.]]


### 08 アイテム$i$の特徴ベクトル

In [10]:
i = 0
print(f'x{i} = {x[i]}')

x0 = [5. 3.]


### 09 評価値集合

In [11]:
ru = Du[:, -1]
print(f'ru = {ru}')

ru = [ 1.  1.  1. -1. -1. -1. -1. nan nan nan nan nan nan]


### 10 評価値集合の形状

In [12]:
print(f'ruの形状 = {ru.shape}')

ruの形状 = (13,)


### 11 評価値集合の全要素数

In [13]:
print(f'ruの全要素数 = {ru.size}')

ruの全要素数 = 13


### 12 評価値集合の部分集合

In [14]:
i = 2
j = 5
print(f'ru{i}からru{j-1}までの評価値 = {ru[i:j]}')

ru2からru4までの評価値 = [ 1. -1. -1.]


### 13 評価値集合の逆順

`ru[::-1]`により、逆順で値を取り出す。

In [15]:
print(f'ruの逆順 = {ru[::-1]}')

ruの逆順 = [nan nan nan nan nan nan -1. -1. -1. -1.  1.  1.  1.]


### 14 アイテム$i$に対する評価

`ru[i]`を使う。

In [16]:
i = 0
print(f'ru{i} = {ru[i]}')

ru0 = 1.0


## アイテム集合

### 15 ユーザ$u$が未評価であるか否かの判定

ここでは、評価値$r_u$について、その第$i$成分が`np.nan`であるときユーザー$u$がアイテム$i$を未評価であるとして問題を解く。

`np.isnan(nparray)`を使う。

In [17]:
print(f'ユーザuが未評価 = {np.isnan(ru)}')

ユーザuが未評価 = [False False False False False False False  True  True  True  True  True
  True]


### 16 ユーザ$u$が評価済みであるか否かの判定

`np.isnan(nparray)`に対して、`~`をつけてあげれば`True`と`False`が反転するので題意を満たす。

In [18]:
print(f'ユーザuが評価済み = {~np.isnan(ru)}')

ユーザuが評価済み = [ True  True  True  True  True  True  True False False False False False
 False]


### 17 ユーザ$u$が評価済みのアイテム集合$I_u$

16で見た評価済みのアイテムのみを抽出する。

`np.arange()`について、16の結果を使ってインデキシングすることで解決する。

In [19]:
Iu = np.arange(ru.shape[0])[~np.isnan(ru)]
print(f'Iu = {Iu}')

Iu = [0 1 2 3 4 5 6]


### 18 ユーザ$u$が好きと評価したアイテム集合$I_{u+}$

ユーザ$u$が評価済みで、なおかつ評価値が$1$であるようなアイテム集合$I_u$を作る。

`np.where(ruの条件, True, False)`を使う。

In [20]:
Iuplus = np.arange(ru.shape[0])[np.where(ru == 1, True, False)]
print(f'Iu+ = {Iuplus}')

Iu+ = [0 1 2]


### 19 ユーザ$u$が嫌いと評価したアイテム集合$I_{u-}$

`np.where()`の条件部分をいじればよい。

In [21]:
Iuminus = np.arange(ru.shape[0])[np.where(ru == -1, True, False)]
print(f'Iu- = {Iuminus}')

Iu- = [3 4 5 6]


### 20 ユーザ$u$が未評価のアイテム集合$\bar{I}_u$

1. `np.nan`かどうかでインデキシングする。
2. `numpy.setdiff1d()`については、また今度。

In [22]:
Iu_not = np.arange(ru.shape[0])[np.isnan(ru)]
print(f'Iu_not = {Iu_not}')

Iu_not = [ 7  8  9 10 11 12]


## 訓練データと予測対象データ

### 21 訓練データ

17でやったインデキシングを`Du`に直接適用すればできるはず。

In [23]:
DuL = Du[~np.isnan(ru)]
print(f'DuL = \n{DuL}')

DuL = 
[[ 5.  3.  1.]
 [ 6.  2.  1.]
 [ 4.  1.  1.]
 [ 8.  5. -1.]
 [ 2.  4. -1.]
 [ 3.  6. -1.]
 [ 7.  6. -1.]]


### 22 訓練事例数

`np.shape`で`DuL`の行数を求めればよい。

In [24]:
print(f'|DuL| = {DuL.shape[0]}')

|DuL| = 7


### 23 正事例数

`np.where(ruの条件, True, False)`の長さは13なので、これでインデキシングしたい場合`DuL`を対象としてもエラーが発生する。(一敗)

そのため今回は`DuL[:, -1]`、つまり`DuL`の中でも評価値の部分に対して`np.where`を利用した。

In [25]:
print(f'|DuL+| = {DuL[np.where(DuL[:, -1] == 1, True, False)].shape[0]}')

|DuL+| = 3


### 24 不事例数

In [26]:
print(f'|DuL-| = {DuL[np.where(DuL[:, -1] == -1, True, False)].shape[0]}')

|DuL-| = 4


### 25 予測対象事例数

21でやったこととほぼ同じことをやればよい。`~`を外すだけ。

In [27]:
DuU = Du[np.isnan(ru)]
print(f'DuU = \n{DuU}')

DuU = 
[[ 4.  2. nan]
 [ 5.  1. nan]
 [ 8.  6. nan]
 [ 3.  4. nan]
 [ 4.  7. nan]
 [ 4.  4. nan]]


### 26 予測対象事例数

対象を`DuU`として、22と同じことを行う。

In [28]:
print(f'|DuU| = {DuU.shape[0]}')

|DuU| = 6


## 第2章 評価値行列

準備

In [29]:
import pprint
import numpy as np
np.set_printoptions(precision=3)

## 評価値行列

### 01 評価値行列の生成

正確に内容をトレースし、`np.nan`と`np.array`を使う。

In [30]:
R_list = [[np.nan, 4, 3, 1, 2, np.nan],
          [5, 5, 4, np.nan, 3, 3],
          [4, np.nan, 5, 3, 2, np.nan],
          [np.nan, 3, np.nan, 2, 1, 1],
          [2, 1, 2, 4, np.nan, 3]]

R = np.array(R_list)

In [31]:
print(f'R = \n{R}')

R = 
[[nan  4.  3.  1.  2. nan]
 [ 5.  5.  4. nan  3.  3.]
 [ 4. nan  5.  3.  2. nan]
 [nan  3. nan  2.  1.  1.]
 [ 2.  1.  2.  4. nan  3.]]


### 02 ユーザ集合

第1章で親の顔ほど見た`np.arange(np.shape[0])`を使う。

In [32]:
U = np.arange(R.shape[0])
print(f'U = {U}')

U = [0 1 2 3 4]


### 03 アイテム集合

02と同様に、`np.arange(np.shape[1])`でなんとかする。

In [33]:
I = np.arange(R.shape[1])
print(f'I = {I}')

I = [0 1 2 3 4 5]


### 04 ユーザ数

公式のヒント的に`U`に対して`np.size`を使うらしい。行列ではなくベクトルの場合だと`np.shape`との違いがいまいちわからなかったりするので調べておこうと思う。

In [34]:
print(f'|U| = {U.size}')

|U| = 5


### 05 アイテム数

04と同じように書く。

In [35]:
print(f'|I| = {I.size}')

|I| = 6


### 06 評価値

$u$と$i$は与えてもらえるので、インデックスを指定して値を取り出す。

In [36]:
u = 0
i = 1
print(f'r{u}{i} = {R[u, i]}')

r01 = 4.0


## 評価値行列の疎性

### 07 評価値行列の全要素数

第1章では同じような状況で`np.size`を使っていた。今回は、`np.shape[0]*np.shape[1]`で値を取り出してみる。

In [37]:
print(f'Rの全要素数 = {R.shape[0]*R.shape[1]}')

Rの全要素数 = 30


### 08 観測されているか否かの判定

`np.isnan(R)`により`R`の各成分が欠損値かどうかを確認する。今回の場合は観測されているならば`True`とするようなので別途`~`を付け加える必要がある。

In [38]:
print(f'観測値 = \n{~np.isnan(R)}')

観測値 = 
[[False  True  True  True  True False]
 [ True  True  True False  True  True]
 [ True False  True  True  True False]
 [False  True False  True  True  True]
 [ True  True  True  True False  True]]


### 09 評価値行列の観測値数

`np.count.nonzero()`を使えばよいらしい。そのまま真偽値のみで構成された行列に適用すると、`True`の数を数えてくれるようだ。

In [39]:
print(f'|R| = {np.count_nonzero(~np.isnan(R))}')

|R| = 22


### 10 評価値行列の疎性

$sparsity$の定義に基づいて計算すればよい。少しコードが冗長になると思ったので、`R.shape[index]`ではなく`R.size`を使って計算している。

In [40]:
sparsity = (R.size-np.count_nonzero(~np.isnan(R)))/R.size
print(f'sparsity = {sparsity:.3f}')

sparsity = 0.267


## 評価済みアイテム集合

### 11 ユーザ$u$が評価済みのアイテム集合$I_u$

$u$が与えられるので、`R`の`u`行目の中で欠損値ではないインデックスのみを返すようにする。

In [41]:
u = 0
print(f'I{u} = {I[~np.isnan(R[u, :])]}')

I0 = [1 2 3 4]


### 12 各ユーザの評価済みアイテム集合

ポイントは、多分以下だと思う。

- `ndarray`のリストとしてまとめるという点
  - リストにする際に内包表記を利用する点
- pprintを利用する点

In [42]:
Iu = [I[~np.isnan(R[u, :])] for u in range(U.size)]
print('Iu = ')
pprint.pprint(Iu)

Iu = 
[array([1, 2, 3, 4]),
 array([0, 1, 2, 4, 5]),
 array([0, 2, 3, 4]),
 array([1, 3, 4, 5]),
 array([0, 1, 2, 3, 5])]


### 13 ユーザ$u$と$v$の共通の評価済みアイテム集合$I_{u, v}$

$u$と$v$が与えられるので、11のように評価済みアイテムを得てその共通部分をとることで望みのベクトルが得られる。共通部分の取り方は、案内通り`np.intersect1d(ndarray1, ndarray2)`を使えばよい。

In [43]:
u = 0
v = 1
temp_u = Iu[u]
temp_v = Iu[v]
Iuv = np.intersect1d(temp_u, temp_v)
print(f'I{u}{v} = {Iuv}')

I01 = [1 2 4]


### 14 アイテム$i$を評価済みのユーザ集合

$i$が与えられるので、`U`から$i$列目が`np.nan`でないインデックスを返すように`~np.isnan()`を使う。

In [44]:
i = 0
print(f'U{i} = {U[~np.isnan(R[:, i])]}')

U0 = [1 2 4]


### 15 各アイテムの評価済みユーザ集合

11のコードを参考に12のコードを作ったように、14のコードを修正する。

In [45]:
Ui = [U[~np.isnan(R[:, i])] for i in range(I.size)]
print('Ui = ')
pprint.pprint(Ui)

Ui = 
[array([1, 2, 4]),
 array([0, 1, 3, 4]),
 array([0, 1, 2, 4]),
 array([0, 2, 3, 4]),
 array([0, 1, 2, 3]),
 array([1, 3, 4])]


### 16 アイテム$i$とアイテム$j$の両方を評価済みのユーザ集合$U_{i, j}$

13と同じノリで作ることができる。

In [46]:
i = 0
j = 4
temp_i = Ui[i]
temp_j = Ui[j]
Uij = np.intersect1d(temp_i, temp_j)
print(f'U{i}{j} = {Uij}')

U04 = [1 2]


### 17 評価値行列全体の平均評価値

まずは、何も考えずに`R`を`np.mean()`で平均することを考えたい。すると、悲しいことに以下のようになるので`np.nan`を避ける必要がある。

In [47]:
np.mean(R)

nan

ここで、元ネタの記事にもある通り`np.nanmean()`をすることで`np.nan`を除外した平均を算出できる。

In [48]:
print(f'R全体の平均評価値 = {np.nanmean(R):.3f}')

R全体の平均評価値 = 2.864


### 18 各アイテムの平均評価値

便利だった`np.nanmean()`も`np.mean()`と同様に`axis`を設定できるのでそれを素直に行うことで結果を得る。この場合`axis=0`を指定する必要がある。

In [49]:
ri_mean = np.nanmean(R, axis=0)
print(f'ri_mean = {ri_mean}')

ri_mean = [3.667 3.25  3.5   2.5   2.    2.333]


### 19 各ユーザの平均評価値

18の、`axis=1`版を作ればよい。

In [50]:
ru_mean = np.nanmean(R, axis=1)
print(f'ru_mean = {ru_mean}')

ru_mean = [2.5  4.   3.5  1.75 2.4 ]


### 20 評価値ベクトルの形状変換

記載がある通り、`ndarray.reshape()`を使うことで望みの結果を得る。今回は`ru_mean`を縦ベクトルのような表示にすることが目標となっていて、`reshape(-1, 1)`とするのがいいらしいが紛らわしいと思ってしまった。

In [51]:
print(f'ru_mean = \n{ru_mean.reshape(-1, 1)}')

ru_mean = 
[[2.5 ]
 [4.  ]
 [3.5 ]
 [1.75]
 [2.4 ]]


### 21 平均中心化評価値行列

`R - ru_mean`は計算できず、エラーが発生する。ブロードキャストによって計算できそうだと期待してやってみた結果これがでたのでちょっとつらいが`内包表記`によって`R`の差をとるような計算を試みた。理想的な解答とはかなり乖離していると思われるので、あとで調べてメモっておく。

以下、内包表記を利用した計算。一応値は合っているのだが`ndarray.reshape()`を使う方法を思いつかなかったのが悲しい。

In [52]:
rubar = np.array([[rm] * I.size for rm in ru_mean])
R2 = R - rubar
print(f'R\' = \n{R2}')

R' = 
[[  nan  1.5   0.5  -1.5  -0.5    nan]
 [ 1.    1.    0.     nan -1.   -1.  ]
 [ 0.5    nan  1.5  -0.5  -1.5    nan]
 [  nan  1.25   nan  0.25 -0.75 -0.75]
 [-0.4  -1.4  -0.4   1.6    nan  0.6 ]]
