<a href="https://colab.research.google.com/github/yaminabeworks/qiitakiji/blob/main/numpyknock_recsys07.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# recsys-python

推薦システムを作ることで、機械学習を学ぶ。

https://recsyslab.github.io/recsys-python/

## 第1章 評価履歴

準備

In [1]:
import numpy as np

## 評価履歴

### 01 評価履歴の生成

1. `np.nan`を使う。
2. `np.array`を使う。

In [2]:
Du_list = [[5, 3, 1],
           [6, 2, 1],
           [4, 1, 1],
           [8, 5, -1],
           [2, 4, -1],
           [3, 6, -1],
           [7, 6, -1],
           [4, 2, np.nan],
           [5, 1, np.nan],
           [8, 6, np.nan],
           [3, 4, np.nan],
           [4, 7, np.nan],
           [4, 4, np.nan]]

Du = np.array(Du_list)

In [3]:
print(f'Du = \n{Du}')

Du = 
[[ 5.  3.  1.]
 [ 6.  2.  1.]
 [ 4.  1.  1.]
 [ 8.  5. -1.]
 [ 2.  4. -1.]
 [ 3.  6. -1.]
 [ 7.  6. -1.]
 [ 4.  2. nan]
 [ 5.  1. nan]
 [ 8.  6. nan]
 [ 3.  4. nan]
 [ 4.  7. nan]
 [ 4.  4. nan]]


### 02 評価履歴の形状

- `np.shape`を使う。

In [4]:
print(f'Duの形状 = {Du.shape}')

Duの形状 = (13, 3)


### 03 評価履歴の行数

- `np.shape`を使う。

In [5]:
print(f'Duの行数 = {Du.shape[0]}')

Duの行数 = 13


### 04 評価履歴の列数

- `np.shape`を使う。

In [6]:
print(f'Duの列数 = {Du.shape[1]}')

Duの列数 = 3


### 05 評価履歴の全要素数

- `np.size`を使う。
  - おそらく、`np.shape[0]*np.shape[1]`でもよい。

In [7]:
print(f'Duの全要素数 = {Du.size}')

Duの全要素数 = 39


## アイテム

### 06 アイテム集合

アイテムは、インデックスと読み替えてもこの場合差し支えなさそう。

In [8]:
I = np.arange(Du.shape[0])
print(f'I = {I}')

I = [ 0  1  2  3  4  5  6  7  8  9 10 11 12]


### 07 アイテムの特徴ベクトルの集合

numpy行列中にある評価値以外を取り出す。

In [9]:
x = Du[:, :-1]
print(f'x = \n{x}')

x = 
[[5. 3.]
 [6. 2.]
 [4. 1.]
 [8. 5.]
 [2. 4.]
 [3. 6.]
 [7. 6.]
 [4. 2.]
 [5. 1.]
 [8. 6.]
 [3. 4.]
 [4. 7.]
 [4. 4.]]


### 08 アイテム$i$の特徴ベクトル

In [10]:
i = 0
print(f'x{i} = {x[i]}')

x0 = [5. 3.]


### 09 評価値集合

In [11]:
ru = Du[:, -1]
print(f'ru = {ru}')

ru = [ 1.  1.  1. -1. -1. -1. -1. nan nan nan nan nan nan]


### 10 評価値集合の形状

In [12]:
print(f'ruの形状 = {ru.shape}')

ruの形状 = (13,)


### 11 評価値集合の全要素数

In [13]:
print(f'ruの全要素数 = {ru.size}')

ruの全要素数 = 13


### 12 評価値集合の部分集合

In [14]:
i = 2
j = 5
print(f'ru{i}からru{j-1}までの評価値 = {ru[i:j]}')

ru2からru4までの評価値 = [ 1. -1. -1.]


### 13 評価値集合の逆順

`ru[::-1]`により、逆順で値を取り出す。

In [15]:
print(f'ruの逆順 = {ru[::-1]}')

ruの逆順 = [nan nan nan nan nan nan -1. -1. -1. -1.  1.  1.  1.]


### 14 アイテム$i$に対する評価

`ru[i]`を使う。

In [16]:
i = 0
print(f'ru{i} = {ru[i]}')

ru0 = 1.0


## アイテム集合

### 15 ユーザ$u$が未評価であるか否かの判定

ここでは、評価値$r_u$について、その第$i$成分が`np.nan`であるときユーザー$u$がアイテム$i$を未評価であるとして問題を解く。

`np.isnan(nparray)`を使う。

In [17]:
print(f'ユーザuが未評価 = {np.isnan(ru)}')

ユーザuが未評価 = [False False False False False False False  True  True  True  True  True
  True]


### 16 ユーザ$u$が評価済みであるか否かの判定

`np.isnan(nparray)`に対して、`~`をつけてあげれば`True`と`False`が反転するので題意を満たす。

In [18]:
print(f'ユーザuが評価済み = {~np.isnan(ru)}')

ユーザuが評価済み = [ True  True  True  True  True  True  True False False False False False
 False]


### 17 ユーザ$u$が評価済みのアイテム集合$I_u$

16で見た評価済みのアイテムのみを抽出する。

`np.arange()`について、16の結果を使ってインデキシングすることで解決する。

In [19]:
Iu = np.arange(ru.shape[0])[~np.isnan(ru)]
print(f'Iu = {Iu}')

Iu = [0 1 2 3 4 5 6]


### 18 ユーザ$u$が好きと評価したアイテム集合$I_{u+}$

ユーザ$u$が評価済みで、なおかつ評価値が$1$であるようなアイテム集合$I_u$を作る。

`np.where(ruの条件, True, False)`を使う。

In [20]:
Iuplus = np.arange(ru.shape[0])[np.where(ru == 1, True, False)]
print(f'Iu+ = {Iuplus}')

Iu+ = [0 1 2]


### 19 ユーザ$u$が嫌いと評価したアイテム集合$I_{u-}$

`np.where()`の条件部分をいじればよい。

In [21]:
Iuminus = np.arange(ru.shape[0])[np.where(ru == -1, True, False)]
print(f'Iu- = {Iuminus}')

Iu- = [3 4 5 6]


### 20 ユーザ$u$が未評価のアイテム集合$\bar{I}_u$

1. `np.nan`かどうかでインデキシングする。
2. `numpy.setdiff1d()`については、また今度。

In [22]:
Iu_not = np.arange(ru.shape[0])[np.isnan(ru)]
print(f'Iu_not = {Iu_not}')

Iu_not = [ 7  8  9 10 11 12]


## 訓練データと予測対象データ

### 21 訓練データ

17でやったインデキシングを`Du`に直接適用すればできるはず。

In [23]:
DuL = Du[~np.isnan(ru)]
print(f'DuL = \n{DuL}')

DuL = 
[[ 5.  3.  1.]
 [ 6.  2.  1.]
 [ 4.  1.  1.]
 [ 8.  5. -1.]
 [ 2.  4. -1.]
 [ 3.  6. -1.]
 [ 7.  6. -1.]]


### 22 訓練事例数

`np.shape`で`DuL`の行数を求めればよい。

In [24]:
print(f'|DuL| = {DuL.shape[0]}')

|DuL| = 7


### 23 正事例数

`np.where(ruの条件, True, False)`の長さは13なので、これでインデキシングしたい場合`DuL`を対象としてもエラーが発生する。(一敗)

そのため今回は`DuL[:, -1]`、つまり`DuL`の中でも評価値の部分に対して`np.where`を利用した。

In [25]:
print(f'|DuL+| = {DuL[np.where(DuL[:, -1] == 1, True, False)].shape[0]}')

|DuL+| = 3


### 24 不事例数

In [26]:
print(f'|DuL-| = {DuL[np.where(DuL[:, -1] == -1, True, False)].shape[0]}')

|DuL-| = 4


### 25 予測対象データ

21でやったこととほぼ同じことをやればよい。`~`を外すだけ。

In [27]:
DuU = Du[np.isnan(ru)]
print(f'DuU = \n{DuU}')

DuU = 
[[ 4.  2. nan]
 [ 5.  1. nan]
 [ 8.  6. nan]
 [ 3.  4. nan]
 [ 4.  7. nan]
 [ 4.  4. nan]]


### 26 予測対象事例数

対象を`DuU`として、22と同じことを行う。

In [28]:
print(f'|DuU| = {DuU.shape[0]}')

|DuU| = 6


## 第2章 評価値行列

準備

In [29]:
import pprint
import numpy as np
np.set_printoptions(precision=3)

## 評価値行列

### 01 評価値行列の生成

正確に内容をトレースし、`np.nan`と`np.array`を使う。

In [30]:
R_list = [[np.nan, 4, 3, 1, 2, np.nan],
          [5, 5, 4, np.nan, 3, 3],
          [4, np.nan, 5, 3, 2, np.nan],
          [np.nan, 3, np.nan, 2, 1, 1],
          [2, 1, 2, 4, np.nan, 3]]

R = np.array(R_list)

In [31]:
print(f'R = \n{R}')

R = 
[[nan  4.  3.  1.  2. nan]
 [ 5.  5.  4. nan  3.  3.]
 [ 4. nan  5.  3.  2. nan]
 [nan  3. nan  2.  1.  1.]
 [ 2.  1.  2.  4. nan  3.]]


### 02 ユーザ集合

第1章で親の顔ほど見た`np.arange(np.shape[0])`を使う。

In [32]:
U = np.arange(R.shape[0])
print(f'U = {U}')

U = [0 1 2 3 4]


### 03 アイテム集合

02と同様に、`np.arange(np.shape[1])`でなんとかする。

In [33]:
I = np.arange(R.shape[1])
print(f'I = {I}')

I = [0 1 2 3 4 5]


### 04 ユーザ数

公式のヒント的に`U`に対して`np.size`を使うらしい。行列ではなくベクトルの場合だと`np.shape`との違いがいまいちわからなかったりするので調べておこうと思う。

In [34]:
print(f'|U| = {U.size}')

|U| = 5


### 05 アイテム数

04と同じように書く。

In [35]:
print(f'|I| = {I.size}')

|I| = 6


### 06 評価値

$u$と$i$は与えてもらえるので、インデックスを指定して値を取り出す。

In [36]:
u = 0
i = 1
print(f'r{u}{i} = {R[u, i]}')

r01 = 4.0


## 評価値行列の疎性

### 07 評価値行列の全要素数

第1章では同じような状況で`np.size`を使っていた。今回は、`np.shape[0]*np.shape[1]`で値を取り出してみる。

In [37]:
print(f'Rの全要素数 = {R.shape[0]*R.shape[1]}')

Rの全要素数 = 30


### 08 観測されているか否かの判定

`np.isnan(R)`により`R`の各成分が欠損値かどうかを確認する。今回の場合は観測されているならば`True`とするようなので別途`~`を付け加える必要がある。

In [38]:
print(f'観測値 = \n{~np.isnan(R)}')

観測値 = 
[[False  True  True  True  True False]
 [ True  True  True False  True  True]
 [ True False  True  True  True False]
 [False  True False  True  True  True]
 [ True  True  True  True False  True]]


### 09 評価値行列の観測値数

`np.count.nonzero()`を使えばよいらしい。そのまま真偽値のみで構成された行列に適用すると、`True`の数を数えてくれるようだ。

In [39]:
print(f'|R| = {np.count_nonzero(~np.isnan(R))}')

|R| = 22


### 10 評価値行列の疎性

$sparsity$の定義に基づいて計算すればよい。少しコードが冗長になると思ったので、`R.shape[index]`ではなく`R.size`を使って計算している。

In [40]:
sparsity = (R.size-np.count_nonzero(~np.isnan(R)))/R.size
print(f'sparsity = {sparsity:.3f}')

sparsity = 0.267


## 評価済みアイテム集合

### 11 ユーザ$u$が評価済みのアイテム集合$I_u$

$u$が与えられるので、`R`の`u`行目の中で欠損値ではないインデックスのみを返すようにする。

In [41]:
u = 0
print(f'I{u} = {I[~np.isnan(R[u, :])]}')

I0 = [1 2 3 4]


### 12 各ユーザの評価済みアイテム集合

ポイントは、多分以下だと思う。

- `ndarray`のリストとしてまとめるという点
  - リストにする際に内包表記を利用する点
- pprintを利用する点

In [42]:
Iu = [I[~np.isnan(R[u, :])] for u in range(U.size)]
print('Iu = ')
pprint.pprint(Iu)

Iu = 
[array([1, 2, 3, 4]),
 array([0, 1, 2, 4, 5]),
 array([0, 2, 3, 4]),
 array([1, 3, 4, 5]),
 array([0, 1, 2, 3, 5])]


### 13 ユーザ$u$と$v$の共通の評価済みアイテム集合$I_{u, v}$

$u$と$v$が与えられるので、11のように評価済みアイテムを得てその共通部分をとることで望みのベクトルが得られる。共通部分の取り方は、案内通り`np.intersect1d(ndarray1, ndarray2)`を使えばよい。

In [43]:
u = 0
v = 1
temp_u = Iu[u]
temp_v = Iu[v]
Iuv = np.intersect1d(temp_u, temp_v)
print(f'I{u}{v} = {Iuv}')

I01 = [1 2 4]


### 14 アイテム$i$を評価済みのユーザ集合

$i$が与えられるので、`U`から$i$列目が`np.nan`でないインデックスを返すように`~np.isnan()`を使う。

In [44]:
i = 0
print(f'U{i} = {U[~np.isnan(R[:, i])]}')

U0 = [1 2 4]


### 15 各アイテムの評価済みユーザ集合

11のコードを参考に12のコードを作ったように、14のコードを修正する。

In [45]:
Ui = [U[~np.isnan(R[:, i])] for i in range(I.size)]
print('Ui = ')
pprint.pprint(Ui)

Ui = 
[array([1, 2, 4]),
 array([0, 1, 3, 4]),
 array([0, 1, 2, 4]),
 array([0, 2, 3, 4]),
 array([0, 1, 2, 3]),
 array([1, 3, 4])]


### 16 アイテム$i$とアイテム$j$の両方を評価済みのユーザ集合$U_{i, j}$

13と同じノリで作ることができる。

In [46]:
i = 0
j = 4
temp_i = Ui[i]
temp_j = Ui[j]
Uij = np.intersect1d(temp_i, temp_j)
print(f'U{i}{j} = {Uij}')

U04 = [1 2]


### 17 評価値行列全体の平均評価値

まずは、何も考えずに`R`を`np.mean()`で平均することを考えたい。すると、悲しいことに以下のようになるので`np.nan`を避ける必要がある。

In [47]:
np.mean(R)

nan

ここで、元ネタの記事にもある通り`np.nanmean()`をすることで`np.nan`を除外した平均を算出できる。

In [48]:
print(f'R全体の平均評価値 = {np.nanmean(R):.3f}')

R全体の平均評価値 = 2.864


### 18 各アイテムの平均評価値

便利だった`np.nanmean()`も`np.mean()`と同様に`axis`を設定できるのでそれを素直に行うことで結果を得る。この場合`axis=0`を指定する必要がある。

In [49]:
ri_mean = np.nanmean(R, axis=0)
print(f'ri_mean = {ri_mean}')

ri_mean = [3.667 3.25  3.5   2.5   2.    2.333]


### 19 各ユーザの平均評価値

18の、`axis=1`版を作ればよい。

In [50]:
ru_mean = np.nanmean(R, axis=1)
print(f'ru_mean = {ru_mean}')

ru_mean = [2.5  4.   3.5  1.75 2.4 ]


### 20 評価値ベクトルの形状変換

記載がある通り、`ndarray.reshape()`を使うことで望みの結果を得る。今回は`ru_mean`を縦ベクトルのような表示にすることが目標となっていて、`reshape(-1, 1)`とするのがいいらしいが紛らわしいと思ってしまった。

In [51]:
print(f'ru_mean = \n{ru_mean.reshape(-1, 1)}')

ru_mean = 
[[2.5 ]
 [4.  ]
 [3.5 ]
 [1.75]
 [2.4 ]]


### 21 平均中心化評価値行列

`R - ru_mean`は計算できず、エラーが発生する。ブロードキャストによって計算できそうだと期待してやってみた結果これがでたのでちょっとつらいが`内包表記`によって`R`との差をとるような計算を試みた。理想的な解答とはかなり乖離していると思われるので、あとで調べてメモっておく。

以下、内包表記を利用した計算。一応値は合っているのだが`ndarray.reshape()`を使う方法を思いつかなかったのが悲しい。

In [52]:
rubar = np.array([[rm] * I.size for rm in ru_mean])
R2 = R - rubar
print(f'R\' = \n{R2}')

R' = 
[[  nan  1.5   0.5  -1.5  -0.5    nan]
 [ 1.    1.    0.     nan -1.   -1.  ]
 [ 0.5    nan  1.5  -0.5  -1.5    nan]
 [  nan  1.25   nan  0.25 -0.75 -0.75]
 [-0.4  -1.4  -0.4   1.6    nan  0.6 ]]


**以下、第4章と同時に追記**

`ru_mean`ではなく`ru_mean.reshape(-1, 1)`を使えば`R`との差が直接計算できるということに後で気づいたのでコードを次のセルに記載する。

In [53]:
R2 = R - ru_mean.reshape(-1, 1)
print(f'R\' = \n{R2}')

R' = 
[[  nan  1.5   0.5  -1.5  -0.5    nan]
 [ 1.    1.    0.     nan -1.   -1.  ]
 [ 0.5    nan  1.5  -0.5  -1.5    nan]
 [  nan  1.25   nan  0.25 -0.75 -0.75]
 [-0.4  -1.4  -0.4   1.6    nan  0.6 ]]


## 第3章 類似度に基づく推薦

準備

In [54]:
import pprint
import numpy as np

# 上位K件
TOP_K = 3

Du = np.array([
               [5, 3, +1],
               [6, 2, +1],
               [4, 1, +1],
               [8, 5, -1],
               [2, 4, -1],
               [3, 6, -1],
               [7, 6, -1],
               [4, 2, np.nan],
               [5, 1, np.nan],
               [8, 6, np.nan],
               [3, 4, np.nan],
               [4, 7, np.nan],
               [4, 4, np.nan],
])
I = np.arange(Du.shape[0])
x = Du[:,:-1]
ru = Du[:,-1]

Iu = I[~np.isnan(ru)]
Iup = I[ru==+1]
Iun = I[ru==-1]
Iu_not = np.setdiff1d(I, Iu)

## ユーザプロファイル

### 01 好きなアイテム集合に含まれるアイテムの特徴ベクトルの集合

`x`は以下の通りであるから、`ru`が`1`となっているインデックスのみが`True`になるようなベクトルを使ってあげればよいはず。

In [55]:
x

array([[5., 3.],
       [6., 2.],
       [4., 1.],
       [8., 5.],
       [2., 4.],
       [3., 6.],
       [7., 6.],
       [4., 2.],
       [5., 1.],
       [8., 6.],
       [3., 4.],
       [4., 7.],
       [4., 4.]])

従って、以下のように書くことで答えを得た。`np.where()`を用いることによって、`ru`の値が`1`のところのみ`True`になるようにしている。

In [56]:
print(f'x[Iu+] = \n{x[np.where(ru == 1, True, False)]}')

x[Iu+] = 
[[5. 3.]
 [6. 2.]
 [4. 1.]]


### 02 特徴ベクトルの総和

これは、01で得た`Iu+`に対して、`axis`を工夫して総和をとればよいはずだ。今回は行方向に和をとるはずだから、`axis=0`を使えばいいかもしれない。

In [57]:
print(f'sum(x[Iu+]) = {x[np.where(ru == 1, True, False)].sum(axis=0)}')

sum(x[Iu+]) = [15.  6.]


### 03 ユーザプロファイル

02のコードについて、総和ではなく平均をとるように修正すればよい。

In [58]:
pu = x[np.where(ru == 1, True, False)].mean(axis=0)
print(f'pu = {pu}')

pu = [5. 2.]


## コサイン類似度

### 04 ベクトルの内積

ここでは、04から06までの3問を解いて一部コードを与えられた関数`cos`を完成させることを考える。

内積`num`は、よく用いられる`@`か`np.dot()`を利用して計算されるので今回もそれを用いて計算していく。

### 05 ユーザプロファイルのノルム

ユーザプロファイルのノルム`den_u`は、`np.linalg.norm()`をユーザプロファイルのベクトルに使うことで計算可能なはずだ。引数`ord`は何も設定しない場合デフォルトで`2`になったような気もするが、一応指定はしておく。

### 06 特徴ベクトルのノルム

05のコードに対して、`np.linalg.norm()`の引数に指定するベクトルを`xi`に変更すればよい。

以下では、04から06までの問の答えを用意して`cos`関数を作成し、実行結果を確認している。

In [59]:
def cos(pu, xi):
    """
    コサイン類似度関数：ユーザプロファイルpuとアイテムiの特徴ベクトルxiのコサイン類似度を返す。

    Parameters
    ----------
    pu : ndarray
        ユーザuのユーザプロファイル
    xi : ndarray
        アイテムiの特徴ベクトル

    Returns
    -------
    float
        コサイン類似度
    """
    num = pu@xi
    print(f'num = {num}')
    den_u = np.linalg.norm(pu, ord=2)
    print('den_u = {:.3f}'.format(den_u))
    den_i = np.linalg.norm(xi, ord=2)
    print('den_i = {:.3f}'.format(den_i))
    
    cosine = num / (den_u * den_i)
    return cosine

In [60]:
u = 0
i = 7
print(f'cos(p{u}, x{i}) = {cos(pu, x[i]):.3f}')
u = 0
i = 11
print(f'cos(p{u}, x{i}) = {cos(pu, x[i]):.3f}')

num = 24.0
den_u = 5.385
den_i = 4.472
cos(p0, x7) = 0.997
num = 34.0
den_u = 5.385
den_i = 8.062
cos(p0, x11) = 0.783


## 推薦

### 07 各アイテムに対するスコア

ここでは、07と08の問題を解いて一部コードを与えられた関数`order`を完成させることを考える。

結果から、変数`scores`は、以下のような条件を満たす辞書型の変数となる。
- キーは`np.nan`だったアイテムのインデックス
  - `Iu_not`があるのでこれを用いる
- バリューはキーのアイテムベクトルとユーザプロファイルのスコアをとったもの

これらを満たすよう、今回は辞書の内包表記を用いて記述する。

### 08 推薦リスト

単純に辞書型の変数`scores`をバリューによって並び替えればよい。引数`reverse`を`True`にすることで降順にする点もポイント。

以下では、07から08までの問の答えを用意して`order`関数を作成し、実行結果を確認している。`cos`関数をそのまま実行すると`print`文が実行されてしまうので、`cos2`関数を用意してプリントされないようにしている。

In [61]:
def cos2(pu, xi):
    """
    コサイン類似度関数：ユーザプロファイルpuとアイテムiの特徴ベクトルxiのコサイン類似度を返す。

    Parameters
    ----------
    pu : ndarray
        ユーザuのユーザプロファイル
    xi : ndarray
        アイテムiの特徴ベクトル

    Returns
    -------
    float
        コサイン類似度
    """
    num = pu@xi
    den_u = np.linalg.norm(pu, ord=2)
    den_i = np.linalg.norm(xi, ord=2)
    
    cosine = num / (den_u * den_i)
    return cosine

In [62]:
def score(u, i):
    """
    スコア関数：ユーザuのアイテムiに対するスコアを返す。

    Parameters
    ----------
    u : int
        ユーザuのID（ダミー）
    i : int
        アイテムiのID

    Returns
    -------
    float
        スコア
    """
    return cos2(pu, x[i])

In [63]:
def order(u, I):
    """
    順序付け関数：アイテム集合Iにおいて、ユーザu向けの推薦リストを返す。

    Parameters
    ----------
    u : int
        ユーザuのID
    I : ndarray
        アイテム集合

    Returns
    -------
    list
        タプル(アイテムID: スコア)を要素にした推薦リスト
    """
    scores = {i: score(u, i) for i in I}
    print('scores = ')
    pprint.pprint(scores)
    rec_list = sorted(scores.items(), key=lambda x:x[1], reverse=True)[:TOP_K]
    return rec_list

In [64]:
u = 0
rec_list = order(u, Iu_not)
print('rec_list = ')
for i, scr in rec_list:
    print('{}: {:.3f}'.format(i, scr))

scores = 
{7: 0.9965457582448796,
 8: 0.9832820049844603,
 9: 0.9656157585206697,
 10: 0.8541985556144386,
 11: 0.783110847498294,
 12: 0.9191450300180578}
rec_list = 
7: 0.997
8: 0.983
9: 0.966


## 第4章 $k$近傍法

準備

In [65]:
import pprint
import numpy as np
np.set_printoptions(precision=3)

# 上位K件
TOP_K = 3
# 近傍アイテム数
K_ITEMS = 3
# しきい値
THETA = 0

Du = np.array([
               [5, 3, +1],
               [6, 2, +1],
               [4, 1, +1],
               [8, 5, -1],
               [2, 4, -1],
               [3, 6, -1],
               [7, 6, -1],
               [4, 2, np.nan],
               [5, 1, np.nan],
               [8, 6, np.nan],
               [3, 4, np.nan],
               [4, 7, np.nan],
               [4, 4, np.nan],
])
I = np.arange(Du.shape[0])
x = Du[:,:-1]
ru = Du[:,-1]

Iu = I[~np.isnan(ru)]
Iup = I[ru==+1]
Iun = I[ru==-1]
Iu_not = np.setdiff1d(I, Iu)

## 距離

### 01 ユークリッド距離

この問題では、一部コードを与えられた関数`dist`を完成させる。`dist`では2つのベクトルを入力としてそのユークリッド距離を返すものなので、2つのベクトルの差に対して`np.linalg.norm`を使えばよいはずだ。

In [66]:
def dist(xi, xj):
    """
    距離関数：アイテムiの特徴ベクトルxiとアイテムjの特徴ベクトルxjのユークリッド距離を返す。

    Parameters
    ----------
    xi : ndarray
        アイテムiの特徴ベクトル
    xj : ndarray
        アイテムjの特徴ベクトル

    Returns
    -------
    float
        ユークリッド距離
    """
    distance = np.linalg.norm(xi-xj, ord = 2)
    return distance

In [67]:
i = 7
j = 2
print(f'dist(x{i}, x{j}) = {dist(x[i], x[j]):.3f}')
i = 7
j = 3
print(f'dist(x{i}, x{j}) = {dist(x[i], x[j]):.3f}')

dist(x7, x2) = 1.000
dist(x7, x3) = 5.000


## 近傍アイテム

### 02 アイテム-アイテム距離行列

`Iu`と`Iu_not`の両方からアイテムを取り出し、アイテムの持つベクトルの距離を`dist`関数を使って求める問題である。とりあえず`np.array()`により2重内包表記の結果を包むことで答えと同じものが返ってくるようにはしたけど、題意的には正解と言いがたいかもしれない。あと、正直`D[np.ix_(Iu_not,Iu)]`がよくわかっていない。

In [68]:
D = np.array([[dist(x[i], x[j]) for i in Iu] for j in Iu_not])
print(f'D = \n{D}')

D = 
[[1.414 2.    1.    5.    2.828 4.123 5.   ]
 [2.    1.414 1.    5.    4.243 5.385 5.385]
 [4.243 4.472 6.403 1.    6.325 5.    1.   ]
 [2.236 3.606 3.162 5.099 1.    2.    4.472]
 [4.123 5.385 6.    4.472 3.606 1.414 3.162]
 [1.414 2.828 3.    4.123 2.    2.236 3.606]]


### 03 距離の昇順に並べ替えたインデックスの配列

`x`の各行`xindex`と`Iu`に含まれる各アイテム`iu`の持つベクトル`x[iu]`の距離を求めて02と同じように`ndarray`に変換し、`argsort`によって昇順に番号をつけることで望みの結果を得た。

In [69]:
Ii = np.array([[dist(xindex, x[iu]) for iu in Iu] for xindex in x]).argsort()
print(f'Ii = \n{Ii}')

Ii = 
[[0 1 2 4 3 5 6]
 [1 0 2 3 6 4 5]
 [2 0 1 4 5 3 6]
 [3 6 0 1 5 2 4]
 [4 5 0 2 1 6 3]
 [5 4 0 6 1 2 3]
 [6 3 0 5 1 4 2]
 [2 0 1 4 5 3 6]
 [2 1 0 4 3 5 6]
 [3 6 0 1 5 4 2]
 [4 5 0 2 1 6 3]
 [5 6 4 0 3 1 2]
 [0 4 5 1 2 6 3]]


### 04 近傍$k$件のアイテムのインデックス配列

Iiの結果に対して、スライシングすることで最初の`TOP_K`列分だけを抽出する。これを使って評価値が`+1`だったアイテムと近いアイテムがどれであったかを確認することができる。各行の持つ数値の中に3以上のものがあったのならば、「嫌い」と評価したアイテムが最近傍の3件に含まれていることを示している。

In [70]:
Ii = Ii[:, :TOP_K]
print(f'Ii = \n{Ii}')

Ii = 
[[0 1 2]
 [1 0 2]
 [2 0 1]
 [3 6 0]
 [4 5 0]
 [5 4 0]
 [6 3 0]
 [2 0 1]
 [2 1 0]
 [3 6 0]
 [4 5 0]
 [5 6 4]
 [0 4 5]]


### 05 各対象アイテムの近傍アイテム集合

`Iu_not`からアイテムをとってきて、保存した`Ii`からアイテムで行を指定して抽出することを考える。

In [71]:
Ii = {i: Ii[i] for i in Iu_not}
print('Ii = ')
pprint.pprint(Ii)

Ii = 
{7: array([2, 0, 1]),
 8: array([2, 1, 0]),
 9: array([3, 6, 0]),
 10: array([4, 5, 0]),
 11: array([5, 6, 4]),
 12: array([0, 4, 5])}


## 嗜好予測（多数決方式）

### 06 近傍アイテム集合のうち「好き」と評価したアイテム集合

ここでは、06から08の問題を解いて一部コードを与えられた関数`predict1`を完成させる。

06では、`Ii[i]`に`np.isin()`を使ったインデキシングをすることで答えを得る。`Ii[i]`はアイテム集合のうち、距離が近かったアイテム3件の中に「好き」と評価したアイテムが入っているかどうかを判断するための数値が入っている。

### 07 近傍アイテム集合のうち「嫌い」と評価したアイテム集合

07では、06と同様の方法で答えを得ることができる。

### 08 多数決方式による予測評価値

`Iip`と`Iin`に対して`np.size()`を使うことで$i$の近傍アイテム集合中に「好き」と評価したアイテムがいくつあるか、「嫌い」と評価したアイテムがいくつあるかがわかるので、その結果に対して素直にif文を使ってあげればよい。

In [72]:
def predict1(u, i):
    """
    予測関数（多数決方式）：多数決方式によりユーザuのアイテムiに対する予測評価値を返す。

    Parameters
    ----------
    u : int
        ユーザuのID（ダミー）
    i : int
        アイテムiのID

    Returns
    -------
    float
        予測評価値
    """
    Iip = Ii[i][np.isin(Ii[i], Iup)]
    print(f'I{i}+ = {Iip}')
    Iin = Ii[i][np.isin(Ii[i], Iun)]
    print(f'I{i}- = {Iin}')
    if Iip.size > Iin.size:
        rui = 1
    elif Iip.size < Iin.size:
        rui = -1
    else:
        rui = 0
    return rui

In [73]:
u = 0
i = 7
print(f'predict1({u}, {i}) = {predict1(u, i):.3f}')
u = 0
i = 9
print(f'predict1({u}, {i}) = {predict1(u, i):.3f}')

I7+ = [2 0 1]
I7- = []
predict1(0, 7) = 1.000
I9+ = [0]
I9- = [3 6]
predict1(0, 9) = -1.000


## 嗜好予測（平均方式）

### 09 平均方式による予測評価値

06から08で完成させた関数`predict1`を参考に、`rui`の部分を平均方式に修正したものを関数`predict2`として作成する。

In [74]:
def predict2(u, i):
    """
    予測関数（多数決方式）：多数決方式によりユーザuのアイテムiに対する予測評価値を返す。

    Parameters
    ----------
    u : int
        ユーザuのID（ダミー）
    i : int
        アイテムiのID

    Returns
    -------
    float
        予測評価値
    """
    Iip = Ii[i][np.isin(Ii[i], Iup)]
    Iin = Ii[i][np.isin(Ii[i], Iun)]
    rui = (Iip.size - Iin.size)/K_ITEMS
    return rui

In [75]:
u = 0
i = 7
print(f'predict2({u}, {i}) = {predict1(u, i):.3f}')
u = 0
i = 9
print(f'predict2({u}, {i}) = {predict1(u, i):.3f}')

I7+ = [2 0 1]
I7- = []
predict2(0, 7) = 1.000
I9+ = [0]
I9- = [3 6]
predict2(0, 9) = -1.000


## 推薦

### 10 推薦リスト

ここでは、問10を解いて一部コードを与えられた関数`order`を完成させる。そのために、`scores`に格納された値`score(u, i)`が`THETA`未満になるようなペアを除くための工夫を考える。

問題の指定から`score`は`predict2`関数で作るものとして、`scores`の部分をいじる必要がある。ここでは辞書内包表記の中でif文を用いることによって`THETA`未満の値をすべて削除することを考える。

In [76]:
def score(u, i):
    """
    スコア関数：ユーザuのアイテムiに対するスコアを返す。

    Parameters
    ----------
    u : int
        ユーザuのID
    i : int
        アイテムiのID

    Returns
    -------
    float
        スコア
    """
    return predict2(u, i)

In [77]:
def order(u, I):
    """
    順序付け関数：アイテム集合Iにおいて、ユーザu向けの推薦リストを返す。

    Parameters
    ----------
    u : int
        ユーザuのID
    I : ndarray
        アイテム集合

    Returns
    -------
    list
        タプル(アイテムID: スコア)を要素にした推薦リスト
    """
    scores = {i: score(u, i) for i in I if score(u, i) >= THETA}
    rec_list = sorted(scores.items(), key=lambda x:x[1], reverse=True)[:TOP_K]
    return rec_list

In [78]:
u = 0
rec_list = order(u, Iu_not)
print('rec_list = ')
for i, scr in rec_list:
    print('{}: {:.3f}'.format(i, scr))

rec_list = 
7: 1.000
8: 1.000


## 第5章 ユーザベース協調フィルタリング

準備

In [79]:
import pprint
import numpy as np
np.set_printoptions(precision=3)

# 近傍ユーザ数
K_USERS = 3
# 閾値
THETA = 0

R = np.array([
              [np.nan, 4,      3,      1,      2,      np.nan],
              [5,      5,      4,      np.nan, 3,      3     ],
              [4,      np.nan, 5,      3,      2,      np.nan],
              [np.nan, 3,      np.nan, 2,      1,      1     ],
              [2,      1,      2,      4,      np.nan, 3     ],
])
U = np.arange(R.shape[0])
I = np.arange(R.shape[1])
Ui = [U[~np.isnan(R)[:,i]] for i in I]
Iu = [I[~np.isnan(R)[u,:]] for u in U]
ru_mean = np.nanmean(R, axis=1)
R2 = R - ru_mean.reshape((ru_mean.size, 1))

## ピアソンの相関係数

### 01 ピアソンの相関係数（分子）

以下では、01から03の問題を解いて一部コードを与えられた関数`pearson1`を完成させる。

01はピアソンの相関係数の分子を、取得した各ベクトルから計算するというものである。`Iuv`は、ユーザ$u$やユーザ$v$による評価値が存在する列のみを集めた`Iu[u]`や`Iu[v]`の共通項をとることで比較可能なアイテムの評価を取得したものである。これに対し、各ユーザの評価を平均したものを作って差をとり、内積を計算すればよい。

### 02 ピアソンの相関係数の算出（分母左部）

内積を作る際に作ったユーザ$u$に関するベクトルを`rui`として、それに対して`np.linalg.norm(uri, ord = 2)`を使ってあげればよい。

### 03 ピアソンの相関係数の算出（分母右部）

内積を作る際に作ったユーザ$v$に関するベクトルを`rvi`として、それに対して`np.linalg.norm(uvi, ord = 2)`を使ってあげればよい。

In [80]:
def pearson1(u, v):
    """
    評価値行列Rにおけるユーザuとユーザvのピアソンの相関係数を返す。

    Parameters
    ----------
    u : int
        ユーザuのID
    v : int
        ユーザvのID

    Returns
    -------
    float
        ピアソンの相関係数
    """
    Iuv = np.intersect1d(Iu[u], Iu[v])
    # R[u][Iu[u]]とR[v][Iu[v]]のIu[u]とIu[v]の部分をIuvにしてしまい時間を溶かした。
    # ユーザの評価はすべて平均に反映する点に注意が必要かも。
    rui = R[u][Iuv] - R[u][Iu[u]].mean()
    rvi = R[v][Iuv] - R[v][Iu[v]].mean()
    num = np.dot(rui, rvi)
    print(f'num = {num}')
    den_u = np.linalg.norm(rui, ord = 2)
    print(f'den_u = {den_u:.3f}')
    den_v = np.linalg.norm(rvi, ord = 2)
    print(f'den_v = {den_v:.3f}')
    
    prsn = num / (den_u * den_v)
    return prsn

In [81]:
u = 0
v = 1
prsn = pearson1(u, v)
print(f'pearson1({u}, {v}) = {prsn:.3f}')

num = 2.0
den_u = 1.658
den_v = 1.414
pearson1(0, 1) = 0.853


## 平均中心化評価値行列に基づくピアソンの相関係数

### 04 ピアソンの相関係数（分子）

以下では、04から06の問題を解いて一部コードを与えられた関数`pearson2`を完成させる。

04は01と同じようにピアソンの相関係数の分子を、取得した各ベクトルから計算するというものである。`R`でなく`R2`を利用するところが大きな変更点となる。

### 05 ピアソンの相関係数の算出（分母左部）

内積を作る際に作ったユーザ$u$に関するベクトルを`rui`として、それに対して`np.linalg.norm(uri, ord = 2)`を使ってあげればよい。02と違い、`R2`を使う点がポイントとなっている。

### 06 ピアソンの相関係数の算出（分母右部）

03と同様に内積を作る際に作ったユーザ$v$に関するベクトルを`rvi`として、それに対して`np.linalg.norm(uvi, ord = 2)`を使ってあげればよい。`R2`を使う点がポイント。

In [82]:
def pearson2(u, v):
    """
    平均中心化評価値行列R2におけるユーザuとユーザvのピアソンの相関係数を返す。

    Parameters
    ----------
    u : int
        ユーザuのID
    v : int
        ユーザvのID

    Returns
    -------
    float
        ピアソンの相関係数
    """
    Iuv = np.intersect1d(Iu[u], Iu[v])
    
    rui = R2[u][Iuv]
    rvi = R2[v][Iuv]
    num = np.dot(rui, rvi)
    print('num = {}'.format(num))
    den_u = np.linalg.norm(rui, ord = 2)
    print('den_u = {:.3f}'.format(den_u))
    den_v = np.linalg.norm(rvi, ord = 2)
    print('den_v = {:.3f}'.format(den_v))

    prsn = num / (den_u * den_v)
    return prsn

In [83]:
u = 0
v = 1
prsn = pearson2(u, v)
print(f'pearson2({u}, {v}) = {prsn:.3f}')

num = 2.0
den_u = 1.658
den_v = 1.414
pearson2(0, 1) = 0.853


## ユーザ-ユーザ類似度行列

### 07 ユーザ-ユーザ類似度行列

ユーザ対ユーザについてその相関係数を`R2`によって計算するという問題。内包表記で2重リストを作って、`np.array()`すればよさそう。以下では、それらに加えて関数`sim`で利用するのが関数`pearson2`だと各種`print`が発生する問題があったのでそれを取り除いた関数`pearson3`を別途作って対応した。

In [84]:
def pearson3(u, v):
    """
    平均中心化評価値行列R2におけるユーザuとユーザvのピアソンの相関係数を返す。

    Parameters
    ----------
    u : int
        ユーザuのID
    v : int
        ユーザvのID

    Returns
    -------
    float
        ピアソンの相関係数
    """
    Iuv = np.intersect1d(Iu[u], Iu[v])
    
    rui = R2[u][Iuv]
    rvi = R2[v][Iuv]
    num = np.dot(rui, rvi)
    den_u = np.linalg.norm(rui, ord = 2)
    den_v = np.linalg.norm(rvi, ord = 2)

    prsn = num / (den_u * den_v)
    return prsn

In [85]:
def sim(u, v):
    """
    ユーザ類似度関数：ユーザuとユーザvのユーザ類似度を返す。

    Parameters
    ----------
    u : int
        ユーザuのID
    v : int
        ユーザvのID

    Returns
    -------
    float
        ユーザ類似度
    """
    return pearson3(u, v)

In [86]:
S = np.array([[sim (u, v) for u in U] for v in U])
print(f'S = \n{S}')

S = 
[[ 1.     0.853  0.623  0.582 -0.997]
 [ 0.853  1.     0.649  0.968 -0.853]
 [ 0.623  0.649  1.     0.8   -0.569]
 [ 0.582  0.968  0.8    1.    -0.551]
 [-0.997 -0.853 -0.569 -0.551  1.   ]]


## 類似ユーザの選定

### 08 類似度上位k人のユーザ集合

以下では、08と09の問題を解いて一部コードを与えられた処理について完成させる。08ではあらかじめユーザの類似度を与えた行列`S`から作った辞書が与えられていて、キーはユーザ、バリューはまた別の辞書となっていることが`Uu`からわかる。

08では、`Uu`のバリューの中で各キーに対して格納されている辞書を類似度の順番に並べて上位`K_USERS`件のみを残すというものであるため、その辞書のソートを行う。

### 09 類似度がしきい値以上のユーザ集合

09では`Uu`のバリュー側に格納された辞書について、条件式を使ってそのバリューの値が`THETA`未満のものを除外する。

In [87]:
Uu = {u: {v: S[u,v] for v in U if u!=v} for u in U}
print('Uu = ')
pprint.pprint(Uu)
Uu = {u: dict(sorted(Uu[u].items(), key=lambda x:x[1], reverse=True)[:K_USERS]) for u in Uu.keys()}
print('Uu = ')
pprint.pprint(Uu)
Uu = {u: {v[0]: v[1] for v in Uu[u].items() if v[1] >= THETA} for u in Uu.keys()}
print('Uu = ')
pprint.pprint(Uu)
Uu = {u: np.array(list(Uu[u].keys())) for u in U}
print('Uu = ')
pprint.pprint(Uu)

Uu = 
{0: {1: 0.8528028654224417,
     2: 0.6225430174794672,
     3: 0.5816750507471109,
     4: -0.9968461286620518},
 1: {0: 0.8528028654224417,
     2: 0.6488856845230501,
     3: 0.9684959969581863,
     4: -0.8528028654224418},
 2: {0: 0.6225430174794672,
     1: 0.6488856845230501,
     3: 0.7999999999999998,
     4: -0.5685352436149611},
 3: {0: 0.5816750507471109,
     1: 0.9684959969581863,
     2: 0.7999999999999998,
     4: -0.550920031004556},
 4: {0: -0.9968461286620518,
     1: -0.8528028654224418,
     2: -0.5685352436149611,
     3: -0.550920031004556}}
Uu = 
{0: {1: 0.8528028654224417, 2: 0.6225430174794672, 3: 0.5816750507471109},
 1: {0: 0.8528028654224417, 2: 0.6488856845230501, 3: 0.9684959969581863},
 2: {0: 0.6225430174794672, 1: 0.6488856845230501, 3: 0.7999999999999998},
 3: {0: 0.5816750507471109, 1: 0.9684959969581863, 2: 0.7999999999999998},
 4: {1: -0.8528028654224418, 2: -0.5685352436149611, 3: -0.550920031004556}}
Uu = 
{0: {1: 0.8528028654224417, 2: 0.6

## 嗜好予測

### 10 類似ユーザ集合の中でアイテムiを評価済みのユーザ集合

以下では、10と11の問題を解いて一部コードを与えられた関数`predict`について完成させる。

`Uui`は、アイテム`i`を評価したユーザ`Ui[i]`とユーザ`u`の近傍にいるユーザ`Uu[u]`の共通点を、`np.intersect1d()`を使って求めることで作ることができる。

### 11 予測評価値

11では、予測評価値の`Uui`の大きさが`0`でなかった場合に発生する複雑そうな項を作っていく。`sim(u, v)`は`S[u, v]`であったので、`u`に対する`Uui`をインデックスに指定してあげて`ndarray`状のベクトルを取得して計算に用いる。$r^{'}_{v, i}$については`R2[v, i]`が相当する部分だったはずなので`v`部分を`Uui`で指定してあげて計算用の`ndarray`を取得する。こうして取得したベクトルを、前者の`ndarray`は分子の内積計算と分母の絶対値をとった和の計算に、後者の`ndarray`は分子の内積計算に用いればよい。

In [88]:
def predict(u, i):
    """
    予測関数：ユーザuのアイテムiに対する予測評価値を返す。

    Parameters
    ----------
    u : int
        ユーザuのID
    i : int
        アイテムiのID

    Returns
    -------
    float
        ユーザuのアイテムiに対する予測評価値
    """
    Uui = np.intersect1d(Uu[u], Ui[i])
    print(f'U{u}{i} = {Uui}')

    if Uui.size <= 0:
        return ru_mean[u]
    else:
        rui_pred = ru_mean[u] + np.dot(S[u][Uui], R2[:, i][Uui])/np.abs(S[u][Uui]).sum()
    
    return rui_pred

In [89]:
u = 0
i = 0
print('r{}{} = {:.3f}'.format(u, i, predict(u, i)))
u = 0
i = 5
print('r{}{} = {:.3f}'.format(u, i, predict(u, i)))

U00 = [1 2]
r00 = 3.289
U05 = [1 3]
r05 = 1.601


## 評価値行列の補完

### 12 評価値行列の補完

行列状の`R`に対して、`np.nan`の部分のみを予測値`predict(u, i)`で埋めてあげればよい。余計なprintが発生する関係で、ここでは`predict12`関数を別途用意した上で、2重内包表記の各成分を求めつつ最後に`np.array()`で`ndarray`とした`R3`を作った。

In [90]:
def predict12(u, i):
    """
    予測関数：ユーザuのアイテムiに対する予測評価値を返す。

    Parameters
    ----------
    u : int
        ユーザuのID
    i : int
        アイテムiのID

    Returns
    -------
    float
        ユーザuのアイテムiに対する予測評価値
    """
    Uui = np.intersect1d(Uu[u], Ui[i])

    if Uui.size <= 0:
        return ru_mean[u]
    else:
        
        rui_pred = ru_mean[u] + np.dot(S[u][Uui], R2[:, i][Uui])/np.abs(S[u][Uui]).sum()
    
    return rui_pred

In [91]:
R3 = np.array([[predict12(r0, r1) if np.isnan(R[r0, r1]) else R[r0, r1] for r1 in range(R.shape[1])] for r0 in range(R.shape[0])])
print(f'R\'\' = \n{R3}')

R'' = 
[[3.289 4.    3.    1.    2.    1.601]
 [5.    5.    4.    3.449 3.    3.   ]
 [4.    4.747 5.    3.    2.    2.638]
 [2.524 3.    2.384 2.    1.    1.   ]
 [2.    1.    2.    4.    2.4   3.   ]]


## 第6章 アイテムベース協調フィルタリング

準備

In [92]:
import pprint
import numpy as np
np.set_printoptions(precision=3)

# 近傍アイテム数
K_ITEMS = 3
# 閾値
THETA = 0

R = np.array([
              [np.nan, 4,      3,      1,      2,      np.nan],
              [5,      5,      4,      np.nan, 3,      3     ],
              [4,      np.nan, 5,      3,      2,      np.nan],
              [np.nan, 3,      np.nan, 2,      1,      1     ],
              [2,      1,      2,      4,      np.nan, 3     ],
])
U = np.arange(R.shape[0])
I = np.arange(R.shape[1])
Ui = [U[~np.isnan(R)[:,i]] for i in I]
Iu = [I[~np.isnan(R)[u,:]] for u in U]
ru_mean = np.nanmean(R, axis=1)
R2 = R - ru_mean.reshape((ru_mean.size, 1))

## コサイン類似度

### 01 アイテム$i$とアイテム$j$のコサイン類似度

問題01では、一部コードのみ与えられた関数`cos`を完成させていく。することとしては、内積をとるためのベクトルをとるためのインデックスは`Uij`に用意されているのでそれを用いて`R`から`i`と`j`のベクトルを取得することである。

In [93]:
def cos(i, j):
    """
    評価値行列Rにおけるアイテムiとアイテムjのコサイン類似度を返す。

    Parameters
    ----------
    i : int
        アイテムiのID
    j : int
        アイテムjのID

    Returns
    -------
    float
        コサイン類似度
    """
    Uij = np.intersect1d(Ui[i], Ui[j])
    cosine = np.dot(R[Uij, i], R[Uij, j]) / (np.linalg.norm(R[Uij, i]) * np.linalg.norm(R[Uij, j]))
    return cosine

In [94]:
i = 0
j = 4
cosine = cos(i, j)
print(f'cos({i}, {j}) = {cosine:.3f}')

cos(0, 4) = 0.996


## 調整コサイン類似度

### 02 アイテムiとアイテムjの調整コサイン類似度

問題02では、一部コードのみ与えられた関数`adjusted_cos`を完成させていく。することとしては、問題01で作った部分を`R`ではなく`R2`を利用する形に書き直せばよい。

In [95]:
def adjusted_cos(i, j):
    """
    評価値行列R2におけるアイテムiとアイテムjの調整コサイン類似度を返す。

    Parameters
    ----------
    i : int
        アイテムiのID
    j : int
        アイテムjのID

    Returns
    -------
    cosine : float
        調整コサイン類似度
    """
    Uij = np.intersect1d(Ui[i], Ui[j])
    
    Uij = np.intersect1d(Ui[i], Ui[j])
    cosine = np.dot(R2[Uij, i], R2[Uij, j]) / (np.linalg.norm(R2[Uij, i]) * np.linalg.norm(R2[Uij, j]))
    return cosine

In [96]:
i = 0
j = 4
cosine = adjusted_cos(i, j)
print(f'adjusted_cos({i}, {j}) = {cosine:.3f}')

adjusted_cos(0, 4) = -0.868


## アイテム-アイテム類似度行列

### 03 アイテム-アイテム類似度行列

問題03では、アイテム間の類似度行列$S$を作成する。2重内包表記の各成分を、与えられた関数`sim`による計算によって与えればよい。

In [97]:
def sim(i, j):
    """
    アイテム類似度関数：アイテムiとアイテムjのアイテム類似度を返す。

    Parameters
    ----------
    i : int
        アイテムiのID
    j : int
        アイテムjのID

    Returns
    -------
    float
        アイテム類似度
    """
    return adjusted_cos(i, j)

In [98]:
S = np.array([[sim(i, j) for i in I] for j in I])
print('S = \n{}'.format(S))

S = 
[[ 1.     0.842  0.494 -0.829 -0.868 -0.987]
 [ 0.842  1.     0.896 -0.788 -0.91  -0.942]
 [ 0.494  0.896  1.    -0.583 -0.845 -0.514]
 [-0.829 -0.788 -0.583  1.     0.469  0.497]
 [-0.868 -0.91  -0.845  0.469  1.     1.   ]
 [-0.987 -0.942 -0.514  0.497  1.     1.   ]]


## 類似アイテムの選定

### 04 類似度上位k件のアイテム集合

以下では、04と05の問題を解いて一部コードを与えられた処理について完成させる。04ではあらかじめユーザの類似度を与えた行列`S`から作った辞書が与えられていて、キーはユーザ、バリューはまた別の辞書となっていることが`Ii`からわかる。これに対して、少し複雑だが入れ子になっているほうの辞書のバリューによって並べ替えを行う。

### 05 類似度がしきい値以上のアイテム集合

05では`Ii`のバリュー側に格納された辞書について、条件式を使ってそのバリューの値が`THETA`未満のものを除外する。

In [99]:
# アイテム-アイテム類似度行列から対象アイテムを除外した辞書
Ii = {i: {j: S[i,j] for j in I if i != j} for i in I}
print('Ii = ')
pprint.pprint(Ii)
Ii = {i[0]: dict(sorted(i[1].items(), key=lambda x:x[1], reverse=True)[:K_USERS]) for i in Ii.items()}
print('Ii = ')
pprint.pprint(Ii)
Ii = {i: {j[0]: j[1] for j in Ii[i].items() if j[1] >= THETA} for i in Ii.keys()}
print('Ii = ')
pprint.pprint(Ii)
# 各アイテムの類似アイテム集合をまとめた辞書
Ii = {i: np.array(list(Ii[i].keys())) for i in I}
print('Ii = ')
pprint.pprint(Ii)

Ii = 
{0: {1: 0.8418791389638738,
     2: 0.49365474375598073,
     3: -0.8291725540450335,
     4: -0.8682431421244593,
     5: -0.987241120712647},
 1: {0: 0.8418791389638738,
     2: 0.896314672184623,
     3: -0.7876958617794716,
     4: -0.9099637547345425,
     5: -0.9419581446623225},
 2: {0: 0.49365474375598073,
     1: 0.896314672184623,
     3: -0.5833076828172804,
     4: -0.8451542547285166,
     5: -0.5144957554275266},
 3: {0: -0.8291725540450335,
     1: -0.7876958617794716,
     2: -0.5833076828172804,
     4: 0.4685212856658182,
     5: 0.49665813370370504},
 4: {0: -0.8682431421244593,
     1: -0.9099637547345425,
     2: -0.8451542547285166,
     3: 0.4685212856658182,
     5: 1.0},
 5: {0: -0.987241120712647,
     1: -0.9419581446623225,
     2: -0.5144957554275266,
     3: 0.49665813370370504,
     4: 1.0}}
Ii = 
{0: {1: 0.8418791389638738, 2: 0.49365474375598073, 3: -0.8291725540450335},
 1: {0: 0.8418791389638738, 2: 0.896314672184623, 3: -0.7876958617794716},
 2

## 嗜好予測

### 06 類似アイテム集合の中でユーザuが評価値を与えているアイテム集合

`Iiu`は、ユーザ`u`が評価したアイテム`Iu[u]`とアイテム$i$の近傍にあるアイテム`Ii[i]`の共通点を、`np.intersect1d()`を使って求めることで作ることができる。

### 07 予測評価値

07では、予測評価値の`Iiu`の大きさが`0`でなかった場合に発生する複雑そうな項を作っていく。やっていることは基本的に第5章の11に書いた操作で、対象の変数を変えた以外は同じと考えてもさしつかえないように思う。

In [100]:
def predict(u, i):
    """
    予測関数：ユーザuのアイテムiに対する予測評価値を返す。

    Parameters
    ----------
    u : int
        ユーザuのID
    i : int
        アイテムiのID
    
    Returns
    -------
    float
        ユーザuのアイテムiに対する予測評価値
    """
    Iiu = np.intersect1d(Ii[i], Iu[u])
    print(f'I{i}{u} = {Iiu}')

    if Iiu.size <= 0:
        return ru_mean[u]
    else:
        rui_pred = ru_mean[u] + np.dot(S[i][Iiu], R2[u, :][Iiu])/np.abs(S[i][Iiu]).sum()
    return rui_pred

In [101]:
u = 0
i = 0
print(f'r{u}{i} = {predict(u, i):.3f}')
u = 0
i = 5
print(f'r{u}{i} = {predict(u, i):.3f}')

I00 = [1 2]
r00 = 3.630
I50 = [3 4]
r05 = 1.668


## 第7章 評価履歴の次元削減

準備

In [102]:
import numpy as np
import numpy.linalg as LA
np.set_printoptions(precision=3)

# 縮約後の次元数
DIM = 2

Du = np.array([
               [5, 3, 3, +1],
               [6, 2, 5, +1],
               [4, 1, 5, +1],
               [8, 5, 9, -1],
               [2, 4, 2, -1],
               [3, 6, 5, -1],
               [7, 6, 8, -1],
               [4, 2, 3, np.nan],
               [5, 1, 8, np.nan],
               [8, 6, 6, np.nan],
               [3, 4, 2, np.nan],
               [4, 7, 5, np.nan],
               [4, 4, 4, np.nan],
])
I = np.arange(Du.shape[0])
x = Du[:,:-1]
ru = Du[:,-1]

## 分散共分散行列

### 01 各特徴量の平均値

結果欄から、`x`の行方向つまり`axis=0`について平均をとればよい。

In [103]:
xk_mean = x.mean(axis=0)
print('xk_mean = {}'.format(xk_mean))

xk_mean = [4.846 3.923 5.   ]


### 02 各特徴量の分散

01と同様にvarで分散をとればよい。求める値は、数式から見ても不偏分散ではないことに注意。

In [104]:
s2 = x.var(axis=0)
print(f's^2 = {s2}')

s^2 = [3.361 3.763 4.769]


### 03 各特徴量の標準化

01と02の結果を用いて、標準化を行う。`numpy`のブロードキャストによって単純に差や商をとる計算が使えるので普通に計算すればよい。一応、`np.sqrt()`を使う必要があることに注意。

In [105]:
x2 = (x - xk_mean) / np.sqrt(s2)
print(f'x\' = \n{x2}')

x' = 
[[ 0.084 -0.476 -0.916]
 [ 0.629 -0.991  0.   ]
 [-0.462 -1.507  0.   ]
 [ 1.72   0.555  1.832]
 [-1.552  0.04  -1.374]
 [-1.007  1.071  0.   ]
 [ 1.175  1.071  1.374]
 [-0.462 -0.991 -0.916]
 [ 0.084 -1.507  1.374]
 [ 1.72   1.071  0.458]
 [-1.007  0.04  -1.374]
 [-0.462  1.586  0.   ]
 [-0.462  0.04  -0.458]]


### 04 標準化された特徴量$k$と特徴量$l$の共分散

03で計算済みの`x2`を用いて共分散を求めるとよい。`np.cov`の引数で`bias=True`を用いることで不偏分散ではない分散を求めることができる。

In [106]:
k = 0
l = 1
skl = np.cov(x2[:, k], x2[:, l], bias = True)[0, 1]
print(f's{k}{l} = {skl:.3f}')

s01 = 0.191


### 05 分散共分散行列

04でも使った`np.cov`を使って分散共分散行列を求めればよい。ただ、`np.cov`にそのまま`x2`を入れると行対行の分散共分散行列が作られるので`x2.T`という転置したものを引数に指定する。

In [107]:
S = np.cov(x2.T, bias = True)
print(f'S = \n{S}')

S = 
[[1.    0.191 0.749]
 [0.191 1.    0.163]
 [0.749 0.163 1.   ]]


## 固有値・固有ベクトル

### 06 固有値・固有ベクトル

問題の案内にもある通り、`np.linalg.eig()`を利用して固有値と固有ベクトルを求める。

In [108]:
lmd, v = LA.eig(S)
print(f'λ = {lmd}')
print(f'v = \n{v}')

λ = [1.826 0.25  0.924]
v = 
[[-0.679 -0.71   0.186]
 [-0.291  0.028 -0.956]
 [-0.674  0.704  0.225]]


### 07 固有値の降順にソートしたインデックス配列

固有値が大きい順に並べた場合のインデックスを求める。そのために`np.argsort()`を用いればよいのだが、今回は降順なので`lmd`を引数に指定する際に符号を逆にしてやる必要がある。

In [109]:
indices = np.argsort(-lmd)
print(f'indices = {indices}')

indices = [0 2 1]


### 08 固有値の降順に固有値配列をソート

`lmd`のインデキシングに`indices`を使ってあげればよい。

In [110]:
lmd = lmd[indices]
print(f'λ = {lmd}')

λ = [1.826 0.924 0.25 ]


### 09 固有値の降順に固有ベクトル配列をソート

`v`の列方向について、`indices`でその順番を指定してあげればよい。

In [111]:
v = v[:, indices]
print(f'v = \n{v}')

v = 
[[-0.679  0.186 -0.71 ]
 [-0.291 -0.956  0.028]
 [-0.674  0.225  0.704]]


### 10 第d主成分までの固有ベクトル

`v`の`DIM`列めまでをスライシングすることによって`V`を作ればよい。

In [112]:
V = v[:, :DIM]
print(f'V = \n{V}')

V = 
[[-0.679  0.186]
 [-0.291 -0.956]
 [-0.674  0.225]]


## 主成分得点

### 11 アイテム$i$の第$k$主成分得点

数式の定義から、主成分得点は`x2`の`i`行めと`v`の`k`列目の内積で得られるのでその通りに計算する。

In [113]:
i = 0
k = 0
xik3 = np.dot(x2[i, :] ,v[:, k])
print(f'x{i}{k}\'\' = {xik3:.3f}')

x00'' = 0.699


### 12 各アイテムの次元削減後の特徴ベクトル

`@`演算子を使って、`x2`と`V`の行列計算を行えばよい。

In [114]:
x3 = x2 @ V
print(f'x\'\' = \n{x3}')

x'' = 
[[ 0.699  0.264]
 [-0.139  1.065]
 [ 0.752  1.355]
 [-2.564  0.202]
 [ 1.969 -0.636]
 [ 0.373 -1.211]
 [-2.035 -0.496]
 [ 1.219  0.656]
 [-0.545  1.766]
 [-1.788 -0.601]
 [ 1.598 -0.535]
 [-0.148 -1.603]
 [ 0.611 -0.227]]


## 寄与率

### 13 第$k$主成分の寄与率

固有値の和の中で第$k$主成分がどれだけの大きさを占めるかを、寄与率と呼んでいる。分散共分散行列はその性質上固有値が0未満にはならないので、分母が`0`になることもなく安心して割合の計算を行うことができたはず。

In [115]:
# k=0とすると第1主成分になる。おそらくインデックスの都合。
k = 0
pk = lmd[k]/lmd.sum()
print(f'第{k+1}主成分の寄与率 = {pk:.3f}')

第1主成分の寄与率 = 0.609


### 14 第k主成分までの累積寄与率

13を参考に、`pk`の分子の部分をスライスした部分の和としてあげればよい。

In [116]:
k = 2
ck = lmd[:k].sum()/lmd.sum()
print(f'第{k}主成分までの累積寄与率 = {ck:.3f}')

第2主成分までの累積寄与率 = 0.917


## 推薦

### 15 次元削減後の評価履歴

`np.hstack()`を使って`x3`と`ru`を横に結合する。`np.hstack()`の引数に`()`を入れないといけないことや、`ru`に`reshape`を使う必要があることに注意。

In [117]:
Du2 = np.hstack((x3, ru.reshape(-1, 1)))
print(f'Du\' = \n{Du2}')

Du' = 
[[ 0.699  0.264  1.   ]
 [-0.139  1.065  1.   ]
 [ 0.752  1.355  1.   ]
 [-2.564  0.202 -1.   ]
 [ 1.969 -0.636 -1.   ]
 [ 0.373 -1.211 -1.   ]
 [-2.035 -0.496 -1.   ]
 [ 1.219  0.656    nan]
 [-0.545  1.766    nan]
 [-1.788 -0.601    nan]
 [ 1.598 -0.535    nan]
 [-0.148 -1.603    nan]
 [ 0.611 -0.227    nan]]
